### ISSUE TITLE
Add GitTogether Chile repo

### ISSUE THREAD

**Issue by AndreaGriffiths11** [IonicaBizau/made-in-chile#16]
Holita! me encantaría incluir en tu lista, una iniciativa comunitaria: https://github.com/gittogethers/santiago

**Comment by IonicaBizau** [comment]
@AndreaGriffiths11 ¡Holaaa! 😁 Muchas gracias, Andrea. Añadí el proyecto al inicio de la lista (la subsección Git). Extraño tanto Sudamerica... 🌎 😁

**Comment by AndreaGriffiths11** [comment]
Muchas gracias!!
