### ISSUE TITLE
Add Variance Ratio test

### ISSUE THREAD

**Issue by LautaroParada** [IonicaBizau/made-in-chile#5]
Hi all, I would like to propose my repository as a new entry in the list. The functionality of this one is related to a statistical test that aims to prove that some financial series have a **predictability component in their structure**. This test can be used as a filter for a machine learning algorithm that trades some financial instruments in an automated fashion.

The test is called the **Variance Ratio Test** and it was designed by *Andrew Lo and Archey Mackinlay*

For a detailed explanation of the test, please visit the papers in which this test is based: 

- Lo, Andrew W. and MacKinlay, Archie Craig, Stock Market Prices Do Not Follow Random Walks: Evidence from a Simple Specification Test (February 1987). NBER Working Paper No. w2168. Available at SSRN: [https://ssrn.com/abstract=346975](https://ssrn.com/abstract=346975)

- Lo, Andrew W. and MacKinlay, Archie Craig, The Size and Power of the Variance Ratio Test in Finite Samples: a Monte Carlo Investigation (June 1988). NBER Working Paper No. t0066. Available at SSRN: [https://ssrn.com/abstract=396681](https://ssrn.com/abstract=396681)

**Comment by IonicaBizau** [comment]
Thanks for sharing that! Is that published on GitHub too?
Currently we list only GitHub repositories.

**Comment by LautaroParada** [comment]
Of course! here is the link https://github.com/LautaroParada/variance-test

**Comment by LautaroParada** [comment]
any updates @IonicaBizau ?

**Comment by IonicaBizau** [comment]
@LautaroParada Please create a pull request with that. I'll be happy to merge it.
