### ISSUE TITLE
Add cliente-API de Indicadores Enconomicos Chile

### ISSUE THREAD

**Issue by LautaroParada** [IonicaBizau/made-in-chile#7]
Este es un cliente de la API que entrega los principales indicadores económicos para Chile en formato Table o struct. Tanto los indicadores diarios como los históricos pueden ser usados por desarrolladores y/o analistas en aplicaciones, analisis, etc.

La API mapea constantemente el sitio del Banco Central de Chile manteniendo así la base de datos actualizada con los últimos valores del día.

La documentación del cliente en Matlab puede ser encontrada en el sitio de repositorio https://github.com/LautaroParada/Indicadores-enconomicos

La documentación oficial de la API puede ser encontrada en el siguiente sitio web https://mindicador.cl/

@IonicaBizau

**Comment by IonicaBizau** [comment]
Usted puede hacer un Pull request para eso. :sparkles: Gracias.
